### ISSUE TITLE
finalize paper draft for Andrew

### ISSUE THREAD

**Issue by jgabry** [jgabry/bayes_R2#3]
@bgoodri @imadmali Anything to add to this before I send Andrew a "final" draft?

**Comment by imadmali** [comment]
On my side the only important thing is if we want to change the way R2 is calculated for bayesian beta regression. In frequentist beta regression they have pseudo-R2 which is the squared correlation between the linear predictor and the link transformed outcome. When `phi` is not modeled as a linear predictor this "fine" but when it is it means you can overfit `phi` without changing the R2, which is kind of weird. It might be better to use one of the shape parameters instead `linkinv(eta) * phi` or `(1-linkinv(eta)) * phi`. This way you're including info about `phi` whether it's treated as a scalar or modeled as a linear predictor. But 1) I'm not sure about using the shape parameter in bayesian R2 and 2) this discussion about betareg R2 seems quite niche and I'm not sure if it should go in this paper or the short paper on bayesian beta regression I've been working on.

A minor thing: in the computation of the residuals in the line of text above equation 3 should it be `y_n` instead of `y_n^s` since we're referring to the data here and there are no draws associated with it?

**Comment by jgabry** [comment]
Could be worth discussing in this one although it does seem more niche so yeah maybe in the beta regression paper? 

And you're right about `y_n` instead of `y_n^s`. Good catch. Just fixed that.

**Comment by imadmali** [comment]
> Could be worth discussing in this one although it does seem more niche so yeah maybe in the beta regression paper?

Fine with me.
